DatisBasePaySolution/src/DatisBasePay/Entities/DatisBasePayDbContext.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace DatisBasePay.Entities
{
	public class DatisBasePayDbContext : IdentityDbContext<User>
	{

		public DatisBasePayDbContext(DbContextOptions options) : base(options)
		{

		}

		public DbSet<Employee> Employees { get; set; }
	}
}

DatisBasePaySolution/src/DatisBasePay/Entities/Employee.cs
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace DatisBasePay.Entities
{
	public class Employee
	{
		public int Id { get; set; }
		[Required, MaxLength(80)]
		public string EmployeeName { get; set; }
		[Required]
		public decimal Salary { get; set; }
		[Required]
		public decimal TaxRate { get; set; }
		[Required]
		public decimal Contribution { get; set; }
		[Required]
		public string StateOfResidence { get; set; }
	}
}

DatisBasePaySolution/src/DatisBasePay/Entities/User.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace DatisBasePay.Entities
{
	public class User : IdentityUser
	{
		// ...
	}
}

DatisBasePaySolution/src/DatisBasePay/ViewModels/EmployeeViewModel.cs
using DatisBasePay.Entities;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DatisBasePay.ViewModels
{
	public class EmployeeViewModel
	{
		public int Id { get; set; }
		[Required]
		[Display(Name = "Employee Name")]
		public string EmployeeName { get; set; }
		[Required]
		public decimal Salary { get; set; }
		[Required]
		[Display(Name = "Tax Rate")]
		public decimal TaxRate { get; set; }
		[Required]
		[Display(Name = "401k Contribution")]
		public decimal Contribution { get; set; }
		[Required]
		[Display(Name = "State of Residence")]
		public string StateOfResidence { get; set; }
		public IEnumerable<Employee> Employees { get; set; }
	}
}

DatisBasePaySolution/src/DatisBasePay/ViewModels/HomePageViewModel.cs
namespace DatisBasePay.ViewModels
{
	public class HomePageViewModel
	{
		public string CurrentMessage { get; set; }
	}
}

DatisBasePaySolution/src/DatisBasePay/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace DatisBasePay.ViewModels
{
	public class LoginViewModel
	{
		[Required]
		public string Username { get; set; }

		[Required, DataType(DataType.Password)]
		public string Password { get; set; }

		[Display(Name = "Remember Me")]
		public bool RememberMe { get; set; }

		public string ReturnUrl { get; set; }
	}
}

DatisBasePaySolution/src/DatisBasePay/ViewModels/RegisterUserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace DatisBasePay.ViewModels
{
	public class RegisterUserViewModel
	{
		[Required, MaxLength(256)]
		public string Username { get; set; }

		[Required, DataType(DataType.Password)]
		public string Password { get; set; }

		[DataType(DataType.Password), Compare(nameof(Password))]
		public string ConfirmPassword { get; set; }
	}
}

DatisBasePaySolution/src/DatisBasePay/Controllers/AccountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using DatisBasePay.Entities;
using DatisBasePay.ViewModels;
using System.Threading.Tasks;

namespace DatisBasePay.Controllers
{
	public class AccountController : Controller
	{
		private SignInManager<User> _signInManager;
		private UserManager<User> _userManager;

		public AccountController(UserManager<User> userManager,
							SignInManager<User> signInManager)
		{
			_userManager = userManager;
			_signInManager = signInManager;
		}

		[HttpGet]
		public IActionResult Register()
		{
			return View();
		}

		[HttpPost, ValidateAntiForgeryToken]
		public async Task<IActionResult> Register(RegisterUserViewModel model)
		{
			if (ModelState.IsValid)
			{
				var user = new User { UserName = model.Username };

				var createResult = await _userManager.CreateAsync(user, model.Password);
				if (createResult.Succeeded)
				{
					await _signInManager.SignInAsync(user, false);
					return RedirectToAction("Index", "Home");
				}
				else
				{
					foreach (var error in createResult.Errors)
					{
						ModelState.AddModelError("", error.Description);
					}
				}
			}
			return View();
		}

		[HttpPost, ValidateAntiForgeryToken]
		public async Task<IActionResult> Logout()
		{
			await _signInManager.SignOutAsync();
			return RedirectToAction("Index", "Home");
		}

		[HttpGet]
		public IActionResult Login()
		{
			return View();
		}

		[HttpPost, ValidateAntiForgeryToken]
		public async Task<IActionResult> Login(LoginViewModel model)
		{
			if (ModelState.IsValid)
			{
				var loginResult = await _signInManager.PasswordSignInAsync(
									   model.Username, model.Password,
									   model.RememberMe, false);
				if (loginResult.Succeeded)
				{
					if (Url.IsLocalUrl(model.ReturnUrl))
					{
						return Redirect(model.ReturnUrl);
					}
					else
					{
						return RedirectToAction("Index", "Home");
					}
				}
			}
			ModelState.AddModelError("", "Could not login");
			return View(model);
		}
	}
}

DatisBasePaySolution/src/DatisBasePay/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using DatisBasePay.Entities;
using DatisBasePay.Services;
using DatisBasePay.ViewModels;

namespace DatisBasePay.Controllers
{
	[Authorize]
	public class HomeController : Controller
	{
		private IEmployeeData _employeeData;

		public HomeController(IEmployeeData employeeData)
		{
			ViewBag.Title = "Datis Base Pay";
			_employeeData = employeeData;
		}

		public IActionResult Index()
		{
			var model = new HomePageViewModel();
			return View(model);
		}

		[HttpGet]
		[Route("Employees")]
		public IActionResult Get()
		{
			var model = new EmployeeViewModel();
			model.Employees = _employeeData.GetAll();
			return Json(model);
		}

		[HttpGet]
		[Route("/Employee/{id}")]
		public IActionResult Get(int id)
		{
			var model = _employeeData.Get(id);
			return Json(model);
		}

		[HttpPost]
		[Route("Employee")]
		public IActionResult Post([FromBody]EmployeeViewModel model)
		{
			if (ModelState.IsValid)
			{
				var employee = new Employee();
				employee.EmployeeName = model.EmployeeName;
				employee.Salary = model.Salary;
				employee.TaxRate = model.TaxRate;
				employee.Contribution = model.Contribution;
				employee.StateOfResidence = model.StateOfResidence;
				employee = _employeeData.Add(employee);
				_employeeData.Commit();
				return Json(employee);
			}
			return View(model);
		}

		[HttpPut]
		[Route("Employee")]
		public IActionResult Update(EmployeeViewModel model)
		{
			var employee = _employeeData.Get(model.Id);
			if (ModelState.IsValid)
			{
				employee.EmployeeName = model.EmployeeName;
				employee.Salary = model.Salary;
				employee.TaxRate = model.TaxRate;
				employee.StateOfResidence = model.StateOfResidence;
				_employeeData.Update(employee);
				_employeeData.Commit();
			}
			return View(employee);
		}

		[HttpDelete]
		[Route("/Employee/{id}")]
		public IActionResult Delete(int id)
		{
			var employee = _employeeData.Get(id);
			_employeeData.Delete(employee);
			_employeeData.Commit();
			return Json(employee);
		}
	}
}

DatisBasePaySolution/src/DatisBasePay/ViewComponents/LoginLogoutViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace DatisBasePay.ViewComponents
{
	public class LoginLogoutViewComponent : ViewComponent
	{
		public IViewComponentResult Invoke()
		{
			return View();
		}
	}
}

DatisBasePaySolution/src/DatisBasePay/Views/Home/Index.cshtml
@model DatisBasePay.ViewModels.HomePageViewModel

<h1>@ViewBag.Title</h1>
<div ng-app="app" ng-controller="EmployeeController as vm" ng-cloak>
	<div class="container">
		<form name="employeeForm" novalidate>
			<!-- ** BEGIN MESSAGE AREA ** -->
			<div ng-hide="vm.uiState.isValid || (employeeForm.$valid && !employeeForm.$pristine)" class="row">
				<div class="col-xs-12">
					<div class="alert alert-danger alert-dismissable" role="alert">
						<button type="button" class="close" data-dismiss="alert">
							<span aria-hidden="true">
								&times;
							</span>
							<span class="sr-only">Close</span>
						</button>
						<ul>
							<li ng-repeat="msg in vm.uiState.messages">
								{{msg.message}}
							</li>
							<li ng-show="employeeForm.employeeName.$error.required">
								Employee name must be filled in.
							</li>
							<li ng-show="employeeForm.salary.$error.required">
								Salary must be greater than 0%.
							</li>
							<li ng-show="employeeForm.taxRate.$error.required">
								Tax Rate must be greater than 0%.
							</li>
							<li ng-show="employeeForm.contribution.$error.required">
								401k Contribution must be  greater than 0%.
							</li>
						</ul>
					</div>
				</div>
			</div>
			<!-- ** END MESSAGE AREA ** -->
			<!-- ** BEGIN SEARCH AREA ** -->
			<div ng-show="vm.uiState.isSearchAreaVisible" class="panel panel-primary">
				<div class="panel-heading">
					<h1 class="panel-title">Search for Employees</h1>
				</div>
				<div class="panel-body">
					<div class="form-group">
						<label for="searchEmployeeName"></label>
						<input type="text" class="form-control"
							  ng-model="search.employeeName" />
					</div>
				</div>
				<div class="panel-footer">
					<button type="button"
						   class="btn btn-sm btn-success"
						   ng-click="vm.addClick()">
						<i class="glyphicon glyphicon-plus"></i>
						&nbsp;Add Employee
					</button>
				</div>
			</div>
			<!-- ** END SEARCH AREA ** -->
			<!-- ** BEGIN DETAIL AREA ** -->
			<div ng-show="vm.uiState.isDetailAreaVisible" class="panel panel-primary">
				<div class="panel-heading">
					<h1 class="panel-title">
						Employee Information
					</h1>
				</div>
				<div class="panel-body">
					<!-- ** BEGIN INPUT AREA -->
					<div class="form-group">
						<label for="employeeName">Employee Name</label>
						<input id="employeeName"
							  name="employeeName"
							  required
							  type="text"
							  class="form-control"
							  ng-minlength="2"
							  ng-maxlength="150"
							  ng-model="vm.employee.EmployeeName" />
					</div>
					<div class="form-group">
						<label for="salary">Salary</label>
						<input id="salary"
							  name="salary"
							  required
							  type="text"
							  class="form-control"
							  ng-model="vm.employee.Salary" />
					</div>
					<div class="form-group">
						<label for="taxRate">Tax Rate %</label>
						<input id="taxRate"
							  name="taxRate"
							  required
							  type="text"
							  class="form-control"
							  ng-model="vm.employee.TaxRate" />
					</div>
					<div class="form-group">
						<label for="contribution">401k Contribution %</label>
						<input id="contribution"
							  name="contribution"
							  required
							  type="text"
							  class="form-control"
							  ng-model="vm.employee.Contribution" />
					</div>
					<div class="form-group">
						<label for="stateOfResidence">State of Residence</label>
						<select id="stateOfResidence" name="stateOfResidence" class="form-control" ng-model="vm.employee.StateOfResidence">
							<option value="Arizona">Arizona</option>
							<option value="Florida">Florida</option>
							<option value="Hawaii">Hawaii</option>
							<option value="Nevada">Nevada</option>
							<option value="Virginia">Virginia</option>
						</select>
					</div>
					<!-- ** END INPUT AREA -->
				</div>
				<div class="panel-footer">
					<div class="row">
						<div class="col-sm-12">
							<button class="btn btn-sm btn-primary"
								   type="button"
								   ng-click="vm.saveClick(employeeForm)">
								<i class="glyphicon glyphicon-floppy-disk"></i>
								&nbsp;Save
							</button>
							<button class="btn btn-sm btn-primary"
								   type="button"
								   ng-click="vm.cancelClick(employeeForm)">
								<i class="glyphicon glyphicon-remove-circle"></i>
								&nbsp;Cancel
							</button>
						</div>
					</div>
				</div>
			</div>
			<!-- ** END DETAIL AREA ** -->
			<!-- ** BEGIN LIST AREA ** -->
			<div ng-show="vm.uiState.isListAreaVisible" class="table-responsive">
				<table id="productTable" class="table table-condensed table-bordered table-striped table-hover">
					<thead>
						<tr>
							<th class="dbp-action-button-column">
								Edit
							</th>
							<th>Employee Name</th>
							<th>Salary</th>
							<th>Tax Rate</th>
							<th>401k Contribution</th>
							<th>State of Residence</th>
							<th>Net Pay</th>
							<th class="dbp-action-button-column">
								Delete
							</th>
						</tr>
					</thead>
					<tbody>
						<tr ng-repeat="employee in vm.employees | filter:search">
							<td class="dbp-action-button-column">
								<a href="#"
								   ng-click="vm.editClick(employee.id)"
								   class="btn btn-default btn-sm">
									<i class="glyphicon glyphicon-edit"></i>
								</a>
							</td>
							<td>{{employee.employeeName}}</td>
							<td>{{employee.salary | currency}}</td>
							<td>{{employee.taxRate | number:0}}%</td>
							<td>{{employee.contribution | number:0}}%</td>
							<td>{{employee.stateOfResidence}}</td>
							<td>{{employee.salary - (((employee.taxRate / 100) * employee.salary) + ((employee.contribution / 100 * employee.salary))) | currency}}</td>
							<td class="dbp-action-button-column">
								<a href="#"
								   ng-click="vm.deleteClick(employee.id)"
								   class="btn btn-default btn-sm">
									<i class="glyphicon glyphicon-trash"></i>
								</a>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<!-- ** END LIST AREA ** -->
		</form>
	</div>
</div>

DatisBasePaySolution/src/DatisBasePay/Views/Shared/Components/LoginLogout/Default.cshtml
@if (User.Identity.IsAuthenticated)
{
	<form method="post" asp-controller="Account" asp-action="Logout" asp-antiforgery="true">
		<span>Hello, @User.Identity.Name</span>
		<span>
			<input class="btn btn-default" type="submit" value="Logout" />
		</span>
	</form>
}
else
{
	<span>
		<a class="btn btn-default" asp-controller="Account" asp-action="Register">Register</a>
	</span>
	<span>
		<a class="btn btn-default" asp-controller="Account" asp-action="Login">Login</a>
	</span>
}

DatisBasePaySolution/src/DatisBasePay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<link href="/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
	<link href="/Content/site.css" rel="stylesheet" />
</head>
<body ng-app="app">
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="/">Datis Base Pay</a>
			</div>
			<div class="navbar-right">
				@await Component.InvokeAsync("LoginLogout")
			</div>
		</div>
	</nav>
	<div class="container">
		@RenderBody()
		<footer>
			@RenderSection("footer", required: false)
		</footer>
	</div>
	<script src="/node_modules/jquery/dist/jquery.js"></script>
	<script src="/node_modules/jquery-validation/dist/jquery.validate.js"></script>
	<script src="/node_modules/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
	<script src="/node_modules/angular/angular.min.js"></script>
	<script src="/app/app.module.js"></script>
	<script src="/app/employee.controller.js"></script>
</body>
</html>